version: "3"
volumes:
  pgadmin-data:
services:
  print-house-postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - 1368:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=printhouse
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d/
  pgadmin:
    image: dpage/pgadmin6
    restart: always
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.co
      PGADMIN_DEFAULT_PASSWORD: password123
